In [2]:
from numpy import random
print(random.randint(1,100))#random integer in given range
print(random.rand())#float number 0-1

51
0.13415560751818345


In [7]:
#create n-dimensional array with random integer  values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[26 70 23]
[[63  3 40 96]
 [63 97 61 20]
 [51 97  3 65]]
[[[51  3]
  [50 46]
  [87 40]
  [18 23]]

 [[49 88]
  [31 40]
  [59 39]
  [77 76]]

 [[92 33]
  [93 97]
  [67 21]
  [81 35]]]


In [9]:
#create n-dimensional array with random floating values
print(random.rand(3))
print(random.rand(3,4))
print(random.rand(3,4,2))

[0.18994688 0.85671176 0.23419392]
[[0.43295069 0.18619483 0.47206714 0.89172159]
 [0.12758723 0.57895502 0.2221382  0.58990551]
 [0.48708143 0.59093032 0.46374405 0.29318918]]
[[[0.08144706 0.43982986]
  [0.28163488 0.36473478]
  [0.32635395 0.33720562]
  [0.35327164 0.06656502]]

 [[0.3193177  0.2905142 ]
  [0.38035398 0.03548702]
  [0.41001918 0.78439134]
  [0.94794972 0.50152142]]

 [[0.1611879  0.88674222]
  [0.92454291 0.30868069]
  [0.11593284 0.83699522]
  [0.22430567 0.94122845]]]


In [11]:
a = random.randint(100,size=(3,2)).ravel()
a

array([86, 58, 29, 56, 43, 41])

In [12]:
#single element will be selected
random.choice(a)

29

In [14]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(3,4))

array([[1, 2, 2, 1],
       [1, 3, 5, 5],
       [2, 2, 1, 3]])

## Pandas:
1. Data manipulation,analysis and cleaning
2. Tabulated,Unlabelled

## Creating a DataFrame
1. using 2 dictionaries

In [3]:
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}
dict2 = {'a':5,'b':6,'c':7,'d':8,'e':9}
data = {"First":dict1,"Second":dict2}
df = pd.DataFrame(data,dtype=np.int32)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [4]:
#simple dictionary --> DataFrame
d1 = {"name":["vaishu","hari","suresh"],"address":["hyd","ndyl","TG"]}
df1 = pd.DataFrame(d1)
df1

name address
0  vaishu     hyd
1    hari    ndyl
2  suresh      TG

In [5]:
#using series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.32,45.3,52.45,25.33,65.3,85.23,6.32,54.55,55.24])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"column1":s1,"column2":s2,"column3":s3}
df3 = pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.32       b
2        3    45.30       c
3        4    52.45       d
4        5    25.33       e
5        6    65.30       f
6        7    85.23       g
7        8     6.32       h
8        9    54.55       i
9       10    55.24       j

### Selecting data from dataframe:
1. loc
2. iloc

In [6]:
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.32       b
2    45.30       c
3    52.45       d
4    25.33       e
5    65.30       f
6    85.23       g
7     6.32       h
8    54.55       i
9    55.24       j

In [7]:
df3["column2"]

0    12.23
1    23.32
2    45.30
3    52.45
4    25.33
5    65.30
6    85.23
7     6.32
8    54.55
9    55.24
Name: column2, dtype: float64

In [8]:
#using single column
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [9]:
df3.loc[0:5,["column1","column2","column3"]]

column1  column2 column3
0        1    12.23       a
1        2    23.32       b
2        3    45.30       c
3        4    52.45       d
4        5    25.33       e
5        6    65.30       f

In [10]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [14]:
df3.iloc[0:4,0:1]

column1
0        1
1        2
2        3
3        4

### Retrieving information of dataframe

In [15]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
column1    10 non-null int64
column2    10 non-null float64
column3    10 non-null object
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [16]:
df3.shape

(10, 3)

In [17]:
df3.columns

Index(['column1', 'column2', 'column3'], dtype='object')

In [18]:
df3.index

RangeIndex(start=0, stop=10, step=1)

### Viewing data from dataframe:
1. head()
2. tail()
3. sample()

In [20]:
df3.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.32       b
2        3    45.30       c

In [21]:
df3.tail()

column1  column2 column3
5        6    65.30       f
6        7    85.23       g
7        8     6.32       h
8        9    54.55       i
9       10    55.24       j

In [23]:
df3.sample(2)

column1  column2 column3
8        9    54.55       i
4        5    25.33       e

In [24]:
df3.describe()

column1    column2
count  10.00000  10.000000
mean    5.50000  42.527000
std     3.02765  25.051025
min     1.00000   6.320000
25%     3.25000  23.822500
50%     5.50000  48.875000
75%     7.75000  55.067500
max    10.00000  85.230000

### Renaming columns:

In [11]:
#renaming column headers
df3 = df3.rename(columns={"column1":"First",
                          "column2":"Second",
                          "column3":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.32     b
2      3   45.30     c
3      4   52.45     d
4      5   25.33     e
5      6   65.30     f
6      7   85.23     g
7      8    6.32     h
8      9   54.55     i
9     10   55.24     j